version: '3.7'

services:
  mysql:
    image: mysql:5.7
    ports: 
      - 3307:3306
    volumes:
       - todo-mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: duc0395322380 
      MYSQL_DATABASE: seedschool

volumes:
  todo-mysql-data:
